= My First-Ever Accepted Pull Request
:author: Theerawat Kiatdarakun
// :docinfo: shared-head
// :docinfodir: ../../../../asciidoctor/
:nofooter:
:revdate: Updated {docdate}
:stylesheet: asciidoctor.css
// :stylesheet: dark-complete.css
:!toc:

== Background
Linux users can use man command to find out how to use a particular command in detail but it can be overwhelming for some. I find it annoying to have to scroll down many lines just to find simple basic usage. This inspired me to use an alternative: tldr command. Instead of displaying everything it displays only common examples like

```
# tldr blkid

blkid

Lists all recognized partitions and their Universally Unique Identifier (UUID).

   (Use arrows to move, type to search or ctrl+c to return. ? for more)

*  List all partitions
   sudo blkid

   List all partitions in a table, including current mountpoints
```

One day I was about to multi boot my Linux distros with LVM and LUKS1 so I search for LVM-related command but unfortunately the "lvremove" page didn't exist. So I decided to make a pull request to add the page.

== Pull Request Process
. Fork from the GitHub repo.
. git clone to my local folder.
. Read Contributing.md. It guides contributors on how to contribute.
. Make a new branch with the same name as the command I would like to add. In this case, lvremove.
. Switch the lvremove branch and add a new page. There are some folder choices here e.g. common, linux. osx, windows. LVM is available for Linux only so I put it in the linux folder.
. Copy another existing page to make the format consistent. After changing it, I pushed to my remote repository.
. On GitHub, click Pull Requests tab.
. Click New Pull Request and then request to merge it. It had to pass the Continuous Integration check (if any) first. It is an automated test probably to prevent the maintainers from being burnt-out.
. Wait until two reviewers came and gave feedbacks. In my case, it was minor changes.
. Revise and commit again to the same branch.
. Wait until they merge to their repo. Done!
