= Anna's Quest Review
:author: Theerawat Kiatdarakun
// :docinfo: shared-head
// :docinfodir: ../../../../asciidoctor/
:nofooter:
:revdate: Updated {docdate}
:stylesheet: asciidoctor.css
:toc: auto
:toc-title: Outline

== Foreword
I do think that the protagonist is very cute, her simple eye attracts me somehow. I already owned Anna's quest from Humble Trove but I still bought from GOG since I like the platform. Not only I got the main game, but I also got the mini prologue to play. The mini prologue is not actually a game but a side-scrolling narrative. Even I like the game story and setting, I find the game is frustrating without some walkthroughs. It is certainly possible to beat without guides but you need to observe everything with probably quite a bit of trial and error navigations/selections. Still, I do think the game is worth the price (1.99 dollars at the time).

== Review
* Gameplay: This is a point-and-click from Daedalic Entertainment. The studio is famous for this genre. The game mechanic includes the reveal of important objects on the current area upon clicking a button, though the player has to find how they interact on his own. From my experience, the game is quite a bit harder than games like Machinarium and Botanicula that I completed without hints. Certain puzzles don't fully make sense to me at all but they are a few.
* Character: The game represents many kinds of characters and displays many aspects of personalities. The main protagonist: Anna, inspires compassion through the unwillingness to harm others, her grandfather also inspires love by protecting others. The game is therefore very suitable for children and of course also to adults alike.
* Story: The story resembles the typical children animations. It reminds me of Rapunzel albeit different in story. The game suggests that nothing is purely black and white and the world is not always a kind place.
* Verdict: The game is suitable for both children and adults. The story is solid in my opinion but can be frustrating at times without a walkthrough. Still, I recommend it to everyone who likes children storybooks/animations and doesn't mind a point-and-click genre and probably some walkthrough hints.

== Summary (Prologue)
=== Pre-Prologue
Once upon a time, there was Anna's grandfather who was bestowed a telekinetic ability. He used this power to help all people so people hold him in high regard. At some point, he did not want fame or attraction so he moved to the west and began his life as an honest farmer in the west while hiding his ability to his family.

=== Prologue (Minigame)
Time had passed until he had a grandchild Anna. He discovered that a telekinetic ability was also bestowed to Anna but he did not tell her about this. Somewhere in the forest was Winfriede, an evil witch. She wished to get Anna's grandfather's telekinetic power so she used magic to make the farm futile. Anna's father went search for food then disappeared in the forest. His wife sought him but also disappeared later. Anna's grandfather then went to the forest only to find that Winfriede is the perpetrator. He used his power to come back to the farm and instructed Anna not to go out no matter what.

Winfriede used magic to worsen the grandfather's health so Anna had no choice but to leave the farm to search for a curer. In the forest, it was Winfriede again who kidnapped Anna to her tower.

== Summary (Main Story)
=== Chapter 1: A Little Experiment
The girl found herself in the strange tower with some seemingly advanced contraption. Winfriede, residing in another tower, conversed with Anna via a speaker, guiding her to use the machine. The glass container was put on her head. Winfriede then asked if anything changes. A short while after that Anna showed her telekinetic ability to bend a spoon. Winfriede was satisfied then disappeared.

Anna found a teddy bear lying on the floor who could speak. His name is ben. He hid his consciousness to the witch. She showed her intention with him to escape. She realized that her power was too weak to escape the building so she examined the machine and successfully upgraded her telekinesis. She attempted to bend the camera just a bit so Winfriede could not see her escaped but the camera instead disappeared! Winfriede then hurriedly walked towards Anna's tower. She used her power to break the door and stepped down to the first floor. She confronted the Witch and used the power to close the front door, preventing the witch to come inside.

=== Chapter 2: The Great Escape
The girl found another way to escape the tower. She went to the basement and the speakable mirror there told her the wizard in Wunderhorn could help her grandfather. He also guides her on how to make a magic amulet that could protect her from the witch. After making it the witch was finally able to break to the house, casting a spell to her. Anna uses her telekinetic to reverse her magic wand and reverse her spell towards her, causing her to become stoned. She and Ben left the tower with Winfriede's spellbook.

=== Chapter 3: The Trials of Wunderhorn
Anna left the tower with Ben. They met Reynard, a fox just before the city. He would be important later. A witch in the city told Anna to exchange her spellbook for the wizard's location. After exchanging it she met the wizardess in her room. She needs 3 things to help her father: the amber orb, the rose in the glass mountain (she returned a baby dragon from Winfriede's tower and befriended with a dragon to get there), and the spellbook she just gave to another witch. It was hard to obtain those, but she made it finally! After giving everything to her she revealed her true form: Winfriede, a princess in disguise who was going to marry to the king. She cast a spell to break Anna's magic amulet. She called guards to jail her in the dungeon below.

=== Chapter 4: A Damsel's Wager with the Devil
Anna found herself in the dungeon with Reynard the fox in the room nearby. She found a true wizard of Wunderhorn in another room nearby, whom she asked about Ben, Winfriede, and her father. He said she needed to either destroy or convince Winfriede to cure her grandfather. After gathering more information in the dungeon, she found that the approval from the devil was needed to hand over to the admin troll to get her and Reynard out. Several efforts were made to reach the devil. At first meet with the devil, he asks to solve two riddles as a condition to get her out. After getting clues she solved them and got out with Reynard. She was determined to disrupt the wedding.

=== Chapter 5: The Judgment of Queen Voigt
From what the wizard in the dungeon said, she needed to find the disappeared queen Jannike to interrupt the wedding. The girl found the way to the castle and learned that Ben was trapped in the castle and the queen was trapped in the glass mountain where she went with the dragon before. She begged Reynard to inform the dragon and carry her to the mountain. During the meeting on the mountain, the queen said she was trapped because it was needed by the magic she cast on her son, Ben into a bear to protect from Winfriede. Later the queen went back to the castle and disrupt the wedding. Winfriede was really mad and was going to destroy the castle. Anna came and touch Winfriede to get into Winfriede's mind.

=== Chapter 6: Two Sisters in a Far Away School
Here in Winfriede's memory appeared a young version of Winfriede in a magic school. Her mother was the teacher there where Winfriede enrolled as a student. Her mother strongly believed in the Wyrd i.e. the destiny is fixated to everybody. Winfriede did not believe that and tried to impress her mother. Together with Hans, her closest friend, they tried to get the amber orb in the river where dangerous creatures, Weissen Frauen, lived. Hans himself went to the river to get her the amber orb but unfortunately, Weissen Frauen dragged him down to his death. Winfriede ran and tried to help him but it was too late. Suddenly her mother and friends came to her at the river. They misunderstood that Winfriede killed Hans. The devil told her mother that the Wyrd of Winfriede is bad and evil so her mother abandoned her. Her sister, Jannike, tried to hold her hand but she refused. Winfriede was very furious, she had been a bad witch from that point on.

Back from memory to the castle, Anna said sorry to Winfriede and tried to hold her hand like what Jannike did before in memory. She refused, got reflected back by Anna, and fell off the cliff. The king and the queen said thanks to Anna but she did not want anything in return. She returned to her grandfather who was cured of illness and lived happily ever since.
