= CSS: Best Practices
:author: Theerawat Kiatdarakun
// :docinfo: shared-head
// :docinfodir: ../../../../asciidoctor/
:nofooter:
:revdate: Updated {docdate}
:stylesheet: asciidoctor.css
:toc: auto
:toc-title: Outline

== Foreword
These best practices can give coders and the future maintainers an easier time to do the job.

== Best Practices
=== Combine Multiple CSS Files with CSS Bundler
This reduces the number of HTTP requests. The client can then view your website faster.

=== Normalize/Reset CSS
Ever wonder why there is an unexpected margin on your website even you don't specify it? That is because each browser has its default CSS values. By adding a predefined stylesheet into the project, you can expect the same default behavior across browsers. This stylesheet can either remove all default styles (reset CSS) or retain some basic default styling (normalize CSS).

=== Prefer External CSS Over Inline Styling and Internal CSS
To make the code more maintainable.

=== Systematically Order Properties and Selectors
There are a lot of ways to do this. I order them alphabetically since everybody familiar with it.

=== Use CSS Preprocessor
CSS Preprocessor improves readability, reusability, and maintainability. I needed the preprocessor for the first time when I wanted to generate like 1000+ random particles with different properties. Only an insane person would want to code with vanilla CSS!

=== Use CSS Methodology
CSS methodology is the formal system to write CSS codes. It not only helps us to scale CSS code better but also makes our code more readable and systematic. The most popular one as of this writing is BEM (Block, Element, Modifier).

. **Block**: an independent component that can be reused.
. **Element**: a part of a block that can't be separated from it. Examples include full name input in a form field.
. **Modifier** Describes the appearance, state, or behavior of a block or an element. It must be used together with a block or an element's class. A meaningful word (like warning rather than red) should be used for the modifier.

Since BEM components usually share the prefixes, it plays very nicely with SCSS preprocessor, for example,
----
/* & symbol denotes the parent element*/
.article {
	background-color: white;
	&__backbtn {
		background-color: transparent;
		&--visible {
			opacity: 1;
		}
		&:hover {
			background-color: red;
		}
	}
}
----

=== Use CSS Minifiers
Extra whitespaces are nice to us since they make codes more readable but also make file size unnecessarily bigger and hence higher bandwidth usage on websites. A CSS minifier comes into play. It eliminates those.

=== Use CSS Vendor Prefixes

When the standard comes out, different browsers may have different implementations. The prefix such as -webkit- for chrome/safari, -moz- for firefox, -ms- for internet explorer, -o- for opera is used to make your code behaves as expected on different browsers. You can visit https://caniuse.com/ to check vendor prefixes.

It can be tedious and unfun to do so. Fortunately, tools like Autoprefixer can automatically parse your CSS and add vendor prefixes. It also has an integration with an automation tool like gulp.js.
