= Cloud Computing Basics (Cloud 101)
:author: Theerawat Kiatdarakun
// :docinfo: shared-head
// :docinfodir: ../../../../asciidoctor/
:nofooter:
:revdate: Updated {docdate}
:stylesheet: asciidoctor.css
:toc: auto
:toc-title: Outline

== Review
====
* Platform: Coursera
* Instructor: Jim Sullivan
* Institution: LearnQuest
* Approximate Duration: 9 hours
====

I got this Coursera course for free from the offer during a coronavirus outbreak in 2020 so I decided to take a shot. I took this course to refresh my knowledge of cloud technology. This is a very short course (probably < 3 hours with some preknowledge). It is basically a guide to cloud computing with a brief explanation of related technologies. The instructor at times reads what is shown on slides and not explains everything appears on it so I personally cannot recommend this course. The links to Wikipedia in the course are prone to errors as everybody can change it.

== Outline
=== What is the Cloud?
The instructor introduces cloud computing services, examples, and their business model. A basic idea of cloud computing is that the end user has no idea about the underlying implementation of the services, everything is a layer of abstraction. It is often scalable and the customer can add or remove resources as needed. Cloud computing does have disadvantages though. The customer is dependent on the cloud provider not only for data but also for security.

=== Levels of Managed Service
Cloud providers offer a console with a suite of cloud services, which can be categorized into three major types.

* Software-as-a-Service (SaaS) is a very popular service based on a subscription model. Examples: accounting, conferencing, and time tracking tools. More concrete examples include Office 365, Gmail, and Salesforce.
* Platform-as-a-Service (PaaS) is a popular developer offering. With PaaS, a developer can develop software without the complexity of having to maintain the underlying platform. It delivers firm with "Top of the Line" development frameworks and tools. Examples: Heroku, Google App Engine.
* Infrastructure-as-a-Service (IaaS) resembles a typical outsourcing model. The firm can outsource the hosting, database, and other specialized technology to a cloud provider. Examples: AWS, Azure, Google Cloud.

Function-as-a-Service (FaaS) is similar to PaaS but it is a form of microservices. FaaS offers processing power, it doesn't store data. Customers only pay for the time used in a runtime environment. Examples: AWS Lambda, Google Functions, Azure Functions.

=== Deployment Models
* Private, Public, Hybrid, HPC, Big Data Cloud

=== Hosting Scenarios
* Bare-metal Computing
* VMs, Docker, and Kubernetes
* On-premises Computing
* Cloud Computing

=== Comparing Cloud Platforms
* Aure, AWS, GCP, IBM Cloud, Salesforce, and Alibaba

=== The Future of Cloud Computing
* Serverless
* Distributed and Decentralized Applications
* Machine Learning and AI
* IoT
