= Sundered Review
:author: Theerawat Kiatdarakun
// :docinfo: shared-head
// :docinfodir: ../../../../asciidoctor/
:nofooter:
:revdate: Updated {docdate}
:stylesheet: asciidoctor.css
:toc: auto
:toc-title: Outline

== Foreword
The first Medroidvania game I finished is Guacamelee! 2. The gradual exploration got me hooked and I could not stop it. That's why I have a love-hate relationship with this genre. So in late 2019, I bought this one from GOG and it did not disappoint me even a bit. I finished at normal difficulty first with 100% progression and all level 4 perks (15 hours), then later replayed in an easy mode with a different build (< 7 hours).

== Review
* General: The game is best described as 2D rogue-like Medroidvania. It has a rogue-like mechanic because you cannot upgrade your skills while exploring, only at the sanctuary so oftentimes you have to die first to upgrade yourself. The hand-drawn art style is absolutely gorgeous. The game is inspired by Lovecraft's mythology. The horror theme matches well with character and art style. The story gradually unfolds throughout the game via the lore.
* Difficulty: I feel that many deaths are expected in this game so don't worry if you die a lot. Many players complain about hordes that sometimes come out of nowhere to surround you and this often leads to death. So if you want to relax I would recommend easy difficulty (others are normal, hard, and insane (unlocked later). The harder difficulties give you fewer shards for upgrade and require more grinding. In my opinion, easy and normal difficulties are the most enjoyable. Expect to farm a bit more if you feel too weak.
* Verdict: I would recommend this game to anyone maybe except those who don't enjoy fighting a group of hordes that occasionally appears. The hand-drawn art makes the game unique and the story setting is quite solid. The game is a step better than Jotun, the creator's previous game which is in my opinion very boring.

== Summary (Prologue)
=== Before the War
The group of people known as Eschaton gathers below the surface in the dystopian world. The Shining Trapezohedron guides them to the god and begins to conduct a ritual to bring their god here to cleanse the earth. On the other hand, a group of elite humans called valkyrie comes to break the ritual. Their leader: general Water wants to capture the Shining Trapezohedron since he thinks it has some uses.

=== The War
The Valkyrie invades the Eschaton's land that results in a prolonged fight between two groups. The interrupted ritual results in the release of the eldritch energy. This leads to a disastrous result, both groups transformed into a twisted form creatures. The elder shards which are essential for the ritual are scattered throughout the realm. The Shining Trapezohedron still waits for someone to come to finish the ritual.

== Summary (Main Story)
=== Desert
The game focuses on Eshe, a woman wandering in the desert. During the sandstorm, she still walks, resisting the wind while hovering her arms against the sand. Unfortunately, she is heading towards the abandoned place of Valkyrie and Eschaton. The unknown force drags her down.

=== The Unknown Land
She falls down to the sanctuary, the Shining Trapezohedron comes and combines with her, granting her offensive and defensive power. From the sanctuary, there are three doors. Each door connects to three different areas. By the game design, she needs to go in the following order.

1. Below the bottom door is the Valkyrie base. She encounters mostly robots. The generator needs to be activated to proceed but that also activates the self-defense system. The regional boss is Krurhal Milarh, a faithful Eschaton priest.
2. The left door leads to the Eschaton city. The horrifying twisted form Eschaton awaiting her here. The boss is Hysteria, a failed Valkyrie.
3. The right door leads to the cathedral. Both Valkyrie and Eschaton live here together. Oh, dear! The bosses are the Valkyrie's and Eschaton's leaders. The endgame perk is likely required to beat them.

=== The Final Encounter
She gets elder shards from defeating bosses except a shard scattered throughout the map. The final boss and the ending depends on how she deals with the shards (destroy or consume). The consumption of an elder shard makes her more powerful but become dehumanized, while destroying an elder shard gives her more shards to upgrade her ability and also Valkyrie's technology.

1. If she destroys all shards in the Valkyrie's contraption, she will make the fellow Shining Trapezohedron really angry. She will fight the Nyarlathotep, the Eschaton's god who wants to take a portal to the earth. Upon defeating him the Shining Trapezohedron will reveal that Nyarlathotep is his physical form then betray her and mix with him. With the help of Valkyrie's canon technology, she defeats him, resulting in the destruction of the only exit portal so she cannot escape forever.
2. If she consumes all shards. She will fight with herself, or the human part that she discarded. After defeating herself she transformed into Humanity, a horrifying monster. After finishing it she will strike the human part of herself, absorbing that monster, then transforms into an evil being. She opens the portal which floods eldritch monsters to the earth.
3. If she does not consume all shards. She will also fight the Nyarlathotep, upon his death the portal opens, sending her back on the earth with the Shining Trapezohedron! Hello Eshe!
