= Specialization: Data Structures and Algorithms
:author: Theerawat Kiatdarakun
// :docinfo: shared-head
// :docinfodir: ../../../../asciidoctor/
:nofooter:
:revdate: Updated {docdate}
:stylesheet: asciidoctor.css
:toc: auto
:toc-title: Outline

== Review
====
* Platform: Coursera
* Instructor: Prof. Alexander S. Kulikov et al.
* National Research University Higher School of Economics
* Approximate Duration: 8 Months, 6 Hours/Week
====

I took this course in 2018 right after finishing an algorithms specialization from Coursera to really  make sure I know some algorithms lol. This specialization offers a lot of coding assignments. There are a variety of languages to choose from in assignments, for example, {cpp}, Python, Javascript, and some other functional programming languages. The runtime limit for each submission depends on the programming languages used, with {cpp} being less forgiving than Python. So I wrote everything in {cpp} 😎. The only submission I submitted only in Python is the third (or fourth) question in the capstone project where my {cpp} didn't pass the time limit :(. I paid 49 dollars for this course and finished within a month. This is the hardest MOOC course by far (from my experience) so I believe newcomers are likely to take longer than a month. One question in the capstone project took me almost a day! Prepare for that.

Content-wise the specialization (6 courses) is about basic data structure and algorithm from basic to more advanced contents. The genome-related courses provide me the insight of the concrete way the algorithm knowledge can contribute to real-life applications. The capstone project is about analyzing the genome sequence. It is hard for me but like every other course in this specialization, there is a healthy amount of hint from the discussion forum. Code copy/paste activity is strongly discouraged of course, but pseudocodes are available. I would recommend this course to anyone.

== Overview
=== Course 1: Algorithmic Toolbox
They introduce you to the stress-test method, which is the way to determine the robustness of the solution. After that, they show algorithms basics such as Fibonacci, GCD, and Big-O Notation. Next, they dive into greedy algorithms topics like a functional knapsack. Then, they focus on divide-and-conquer algorithms like linear search and binary search. Sorting problems are also covered here. The last section of the course is all about dynamic programming that brakes down problems into subproblems. The result of each subproblem can be utilized to find the solution.

=== Course 2: Data Structure
The first part is about the basics of data structure like arrays, linked lists, stacks, queues, trees. Then they go forward to dynamic arrays and amortized analysis. The rest of the topics are priority queues, disjoint sets, hash tables, and binary search trees.

=== Course 3: Algorithms on Graphs
The basics of graphs are covered here. The shortest-path algorithms (by the number of nodes or by weights) are discussed thereafter. At the end, they talk about the minimum spanning tree: the shortest subsets of edges that connect all nodes together.

=== Course 4: Algorithms on Strings
Algorithms on strings are important e.g. in the DNA sequence analysis. The basics such as suffix trees and suffix arrays are covered here. The popular pattern matching algorithm (Knuth-Morris-Pratt) is also covered which is proved to be more efficient than the naive brute force algorithm.

=== Course 5: Advanced Algorithms and Complexity
List of topics: flows in networks, linear programming, NP-complete problems. Most topics here are presented with pseudocodes so even though they are advanced topics the student can finish it. I find the flows in networks assignment hard even if the hint is there.

=== Course 6: Genome Assembly Programming Challenge
It's the final project with 6 assignments. Not all are required to pass. I admit that I didn't complete all of them because I want to complete it within one month (so only 49 dollars spent lol). The questions are very challenging, definitely not for the faint of heart.
